### ISSUE TITLE
How to track down Facestream requests ?

### ISSUE THREAD

**Issue by qonteo** [qonteo/facestream#4]
What and where the configuration files responsible for logging and sending data (images and face's descriptors) from Facestream to Luna? 

Is it a post request?

What is the module of Luna that receive the images? Is there any database manager involved, which one is it?  PGSQL, Aerospike, Influxdb?

**Comment by Athos5228** [comment]
El archivo de configuración que habilita y modifica lo que va a los logs de Facestream es fs3Config.conf, en el campo "logging". Los archivos .log son grabados por defecto en facestream_win_v.3.1.5\bin\log para facestream.

El archivo que define el API request que envía los rostros recortados a Luna es input.json, en el campo "Destination", o en caso de hacer el envío por línea de comando, la opción -Dst del comando Facestream.exe.  Ejemplo:

FaceStream2.exe -Src rtsp://admin:admin@192.168.43.126/ -Dst https://192.168.1.130:9000/4/storage/descriptors?estimate_attributes=1^&estimate_emotions=1

Sí, necesariamente es un POST, debido a que necesita incluír la imagen de rostro dentro del cuerpo o Body del API request para obtener una respuesta.

Luna-api es el servicio a cargo de recibir las imágenes, en particular el API /storage/descriptors. No tengo todos los detalles en cuanto a la base de datos de Luna, pero Aerospike maneja los rostros almacenados en la máquina virtual de Luna, y tiene una interfaz en el puerto :5010 para eliminar descriptores no deseados.
